"use client";

import type { Feedback, Provenance } from "@/types/api";

interface AnalysisFeedbackProps {
  feedback: Feedback | null;
  provenance: Provenance | null;
}

/**
 * The generated half of the result, kept visibly apart from the measured half.
 *
 * Its own card, its own heading, and a line saying a language model wrote it —
 * so nobody reads this prose as a measurement, and nobody reads the numbers in
 * the card above as something a model decided.
 *
 * `feedback === null` on a completed analysis is a normal outcome, not an
 * error: the numbers are produced without a model, so an outage costs the prose
 * and nothing else.
 */
export function AnalysisFeedback({
  feedback,
  provenance,
}: AnalysisFeedbackProps) {
  return (
    <section
      aria-labelledby="feedback-heading"
      className="rounded-xl border border-border bg-surface"
    >
      <header className="border-b border-border p-5">
        <h3 id="feedback-heading" className="text-sm font-medium">
          Feedback
        </h3>
        <p className="mt-1 text-xs leading-relaxed text-muted">
          Written by a language model from the measurements above. It explains
          them; it does not produce them.
        </p>
      </header>

      {feedback === null ? (
        <div className="p-5">
          <p className="text-sm text-muted">
            Feedback isn&apos;t available for this recording. The measurements
            above are unaffected — they were taken without a language model.
          </p>
        </div>
      ) : (
        <div className="space-y-5 p-5">
          <p className="text-sm leading-relaxed">{feedback.summary}</p>

          {feedback.strengths.length > 0 && (
            <div>
              <h4 className="text-xs font-medium uppercase tracking-wide text-positive">
                What worked
              </h4>
              <ul className="mt-2 space-y-1.5">
                {feedback.strengths.map((item) => (
                  <li
                    key={item}
                    className="text-sm leading-relaxed text-muted before:mr-2 before:text-positive before:content-['—']"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {feedback.areas_to_improve.length > 0 && (
            <div>
              <h4 className="text-xs font-medium uppercase tracking-wide text-warning">
                Worth trying
              </h4>
              <ul className="mt-2 space-y-1.5">
                {feedback.areas_to_improve.map((item) => (
                  <li
                    key={item}
                    className="text-sm leading-relaxed text-muted before:mr-2 before:text-warning before:content-['—']"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="rounded-lg bg-surface-raised p-4">
            <h4 className="text-xs font-medium uppercase tracking-wide text-muted">
              Next
            </h4>
            <p className="mt-1.5 text-sm leading-relaxed">
              {feedback.next_action}
            </p>
          </div>
        </div>
      )}

      {provenance && (
        <p className="border-t border-border px-5 py-3 text-xs text-muted">
          Generated by {provenance.provider}
          {provenance.model ? ` (${provenance.model})` : ""}.
        </p>
      )}
    </section>
  );
}
