"""Mock providers for development and tests.

These exist so the analysis pipeline can be built and exercised end to end
before — and without — any real provider. They do not transcribe and they do
not reason. That is the whole point, and it is stated in three places so it
cannot be lost: in the provenance every result carries (``is_mock=True``), in
the demo script's own opening words, and here.

**A mock result must never be presented as genuine analysis.** The provenance
flag is the contract that lets every layer above enforce that.

Determinism is a real requirement, not a convenience. The same file always
produces the same transcript, so a metric computed from a mock run is stable
across runs and can be asserted on. It comes from seeding a local
:class:`random.Random` with a digest of the file's bytes — different recordings
get different demo output, the same recording never changes.
"""

import hashlib
import random
from pathlib import Path
from typing import Final

from app.services.ai.errors import EmptyTranscriptError, ProviderResponseError
from app.services.analysis.metrics import DEFAULT_PAUSE_THRESHOLD_SECONDS
from app.services.analysis.models import (
    Feedback,
    Provenance,
    SpeechMetrics,
    Transcript,
    TranscriptWord,
)
from app.services.audio_analysis.models import (
    AudioFeedback,
    AudioFeedbackRequest,
)

MOCK_PROVIDER_NAME: Final = "mock"

#: Every mock result carries this. Nothing above this layer needs to know how a
#: mock is detected — it checks ``is_mock``.
MOCK_PROVENANCE: Final = Provenance(provider=MOCK_PROVIDER_NAME, model=None, is_mock=True)

#: Above this share of in-tune frames the mock calls the pitch steady. A mock's
#: threshold for a mock's prose; a real provider makes its own judgement.
_STEADY_IN_TUNE_RATIO: Final = 0.75

#: Demo scripts. Each one says what it is in its first sentence, so a mock
#: transcript that somehow reached a screen would still read as a mock. They
#: contain hesitations and sentence boundaries on purpose: the metrics code
#: needs fillers to count and gaps to detect.
_SCRIPTS: Final[tuple[str, ...]] = (
    (
        "This is mock transcript text produced for development, um, and it was not "
        "generated by a real speech to text provider. The recording was not sent "
        "anywhere and it was not transcribed. Every number shown beside this text is, "
        "you know, measured from these words rather than from any audio. Use it only "
        "to check that the analysis pipeline works end to end. When a real provider is "
        "configured, this placeholder disappears."
    ),
    (
        "Mock transcript, uh, variant two. Nothing here was heard by a model. This "
        "sample exists so that the metrics code has words and timings to work with, "
        "and so the interface has something to render. It is, like, deliberately "
        "unremarkable prose. If you are reading this inside the product, the analysis "
        "ran against demo data and not against a recording."
    ),
    (
        "Placeholder transcript number three. Um, this text is generated locally from "
        "a fixed script. No audio was decoded, uploaded or transcribed to produce it. "
        "The word timings are synthetic, so the pauses and the speaking rate describe "
        "this script and, you know, nothing else. Real transcription needs a "
        "configured provider."
    ),
)

#: Synthetic timing model. Word length drives duration; sentence ends get a gap
#: comfortably above the pause threshold so pause detection has something real
#: to find, and ordinary word gaps stay well below it.
_LEAD_IN_SECONDS: Final = 0.4
_WORD_BASE_SECONDS: Final = 0.14
_WORD_PER_CHARACTER_SECONDS: Final = 0.055
_WORD_GAP_SECONDS: Final = 0.06
_SENTENCE_GAP_SECONDS: Final = DEFAULT_PAUSE_THRESHOLD_SECONDS + 0.25
_SENTENCE_ENDINGS: Final = (".", "?", "!")

#: Read in chunks so a 50 MB upload is not held in memory to be hashed.
_HASH_CHUNK_BYTES: Final = 1024 * 1024


def _seed_from_file(audio_path: Path) -> int:
    """A stable seed derived from the file's contents."""
    digest = hashlib.sha256()
    try:
        with audio_path.open("rb") as handle:
            while chunk := handle.read(_HASH_CHUNK_BYTES):
                digest.update(chunk)
    except OSError as exc:
        # The path comes from RecordingStorage, so this is an infrastructure
        # fault rather than bad input. The reason stays out of the message.
        raise ProviderResponseError(MOCK_PROVIDER_NAME, reason=type(exc).__name__) from exc
    return int.from_bytes(digest.digest()[:8], "big")


def _build_words(script: str, rng: random.Random) -> tuple[tuple[TranscriptWord, ...], float]:
    """Lay the script out on a synthetic timeline.

    Returns the timed words and the total duration of the imaginary recording.
    """
    words: list[TranscriptWord] = []
    cursor = _LEAD_IN_SECONDS

    for token in script.split():
        spoken = token.strip("\"'()[],;:")
        if not spoken:
            continue
        letters = len(spoken.rstrip("".join(_SENTENCE_ENDINGS)))
        duration = (
            _WORD_BASE_SECONDS + _WORD_PER_CHARACTER_SECONDS * letters + rng.uniform(0.0, 0.06)
        )
        start = round(cursor, 3)
        end = round(start + duration, 3)
        words.append(TranscriptWord(text=token, start_seconds=start, end_seconds=end))

        if spoken.endswith(_SENTENCE_ENDINGS):
            cursor = end + _SENTENCE_GAP_SECONDS + rng.uniform(0.0, 0.1)
        else:
            cursor = end + _WORD_GAP_SECONDS + rng.uniform(0.0, 0.04)

    return tuple(words), round(cursor + _LEAD_IN_SECONDS, 3)


class MockSpeechToTextProvider:
    """A deterministic stand-in for a real speech-to-text provider.

    It reads the recording only to derive a seed from its bytes; nothing is
    decoded and no audio leaves the machine. The transcript it returns is one of
    the fixed demo scripts above, laid out on a synthetic timeline.

    ``includes_disfluencies`` is set on the result because the demo script is
    verbatim by construction — the hesitations in it were written there — so
    filler counting against it is meaningful. A real provider must only set that
    flag if it genuinely returns verbatim output.
    """

    def __init__(self, *, script: str | None = None) -> None:
        #: Overrides the demo script. Used by tests, including for the
        #: no-speech case; leave unset for normal development use.
        self._script = script

    @property
    def name(self) -> str:
        return MOCK_PROVIDER_NAME

    async def transcribe(self, audio_path: Path) -> Transcript:
        seed = _seed_from_file(audio_path)
        rng = random.Random(seed)

        script = self._script if self._script is not None else _SCRIPTS[seed % len(_SCRIPTS)]
        words, total_seconds = _build_words(script, rng)

        if not words:
            raise EmptyTranscriptError(MOCK_PROVIDER_NAME, reason="no_words_in_script")

        return Transcript(
            text=script.strip(),
            words=words,
            language="en",
            audio_duration_seconds=total_seconds,
            includes_disfluencies=True,
            provenance=MOCK_PROVENANCE,
        )


#: Rate bands used by the mock's canned wording. Ordinary public-speaking
#: guidance, and only ever applied to a rate that was actually measured.
_SLOW_WPM: Final = 110.0
_FAST_WPM: Final = 170.0

_MOCK_NOTICE: Final = (
    "Demo feedback: this was written from a fixed template, not by a language model."
)


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _were(count: int) -> str:
    return "was" if count == 1 else "were"


class MockFeedbackProvider:
    """Deterministic feedback assembled from the metrics it is given.

    Every sentence it can produce is guarded by the metric it describes, so a
    metric that was not measurable simply produces no sentence. That is the
    behaviour a real feedback provider has to match, and testing it here pins
    the rule down before a model is involved.
    """

    @property
    def name(self) -> str:
        return MOCK_PROVIDER_NAME

    async def generate(self, *, transcript: Transcript, metrics: SpeechMetrics) -> Feedback:
        del transcript  # Deliberately unused: the mock reports only measurements.

        summary = [_MOCK_NOTICE, f"The transcript contains {metrics.word_count} words."]
        if metrics.words_per_minute is not None:
            summary.append(f"That is about {metrics.words_per_minute} words per minute.")

        strengths: list[str] = []
        improvements: list[str] = []

        wpm = metrics.words_per_minute
        if wpm is not None:
            if _SLOW_WPM <= wpm <= _FAST_WPM:
                strengths.append(f"Your pace of {wpm} words per minute is easy to follow.")
            elif wpm > _FAST_WPM:
                improvements.append(
                    f"At {wpm} words per minute you are speaking quickly; slowing down "
                    "gives listeners more time."
                )
            else:
                improvements.append(
                    f"At {wpm} words per minute the pace is unhurried, which can read "
                    "as hesitant over a long stretch."
                )

        if metrics.pause_count is not None:
            if metrics.pause_count == 0:
                improvements.append("No pauses were detected, so the delivery runs continuously.")
            elif metrics.longest_pause_seconds is not None:
                strengths.append(
                    f"You paused {_plural(metrics.pause_count, 'time')}, the longest for "
                    f"{metrics.longest_pause_seconds} seconds."
                )

        fillers = metrics.filler_words
        if fillers is not None and fillers.hesitation_count > 0:
            improvements.append(
                f"There {_were(fillers.hesitation_count)} "
                f"{_plural(fillers.hesitation_count, 'hesitation sound')} "
                'such as "um" and "uh".'
            )
        elif fillers is not None:
            strengths.append("No hesitation sounds were detected.")

        if not strengths:
            strengths.append("The recording produced a transcript the metrics could be read from.")
        if not improvements:
            improvements.append("Nothing measurable stood out as needing attention.")

        return Feedback(
            summary=" ".join(summary),
            strengths=tuple(strengths),
            areas_to_improve=tuple(improvements),
            next_action=("Configure a real speech-to-text provider to replace this demo feedback."),
            provenance=MOCK_PROVENANCE,
        )

    async def interpret_audio(self, request: AudioFeedbackRequest) -> AudioFeedback:
        """Deterministic audio feedback, assembled from the measurements given.

        Every sentence is guarded by the measurement it describes, so an
        unavailable measurement simply produces no sentence — the same rule a
        real provider is held to, pinned down here where it can be tested
        without a model.

        Note what it never says: no timbre label from the spectral numbers, no
        physiological range, no score. The mock is the executable statement of
        what the prompt asks Claude for.
        """
        stability = request.stability
        summary = [
            _MOCK_NOTICE,
            f"This recording is {request.duration_seconds:.1f} seconds long, and "
            f"{stability.voiced_frames} of {stability.total_frames} analysed frames "
            "carried a reliable pitch.",
        ]

        strengths: list[str] = []
        improvements: list[str] = []
        pitch_observations: list[str] = []
        range_observations: list[str] = []
        note_observations: list[str] = []
        audio_observations: list[str] = []

        if stability.in_tune_ratio is not None:
            share = round(stability.in_tune_ratio * 100)
            pitch_observations.append(
                f"{share}% of the pitched frames sat within "
                f"{request.in_tune_threshold_cents:.0f} cents of the nearest note, under "
                "the definition this analysis uses."
            )
            if stability.in_tune_ratio >= _STEADY_IN_TUNE_RATIO:
                strengths.append("Most of the pitched time sat close to a note.")
            else:
                improvements.append(
                    "A large share of the pitched time sat away from the nearest note."
                )

        if stability.mean_cents_deviation is not None:
            direction = "flat" if stability.mean_cents_deviation < 0 else "sharp"
            pitch_observations.append(
                f"On average the pitch sat {abs(stability.mean_cents_deviation):.1f} cents "
                f"{direction} of the nearest note."
            )

        if request.pitch is not None:
            range_observations.append(
                f"The range detected in this recording runs from {request.pitch.lowest_note} "
                f"to {request.pitch.highest_note}, a span of {request.pitch.semitone_span} "
                "semitones. That is what this recording contained, not the limit of your voice."
            )

        if request.notes:
            longest = request.notes[0]
            note_observations.append(
                f"Most of the pitched time — {longest.percentage_of_voiced_time:.0f}% — was "
                f"spent around {longest.note_name}. That makes it the most frequent note here, "
                "which is not the same as the best one."
            )

        if request.loudness.clipped_sample_ratio > 0:
            audio_observations.append(
                "Some samples reached full scale, which can reduce how reliable parts of "
                "this analysis are."
            )
        if request.spectral is not None:
            audio_observations.append(
                "Spectral characteristics were measured, but those numbers alone are not "
                "enough to describe the character of a voice."
            )

        if not strengths:
            strengths.append("The recording carried enough pitch for the analysis to run.")
        if not improvements:
            improvements.append("Nothing measurable stood out as needing attention.")

        return AudioFeedback(
            summary=" ".join(summary),
            strengths=tuple(strengths),
            areas_to_improve=tuple(improvements),
            pitch_observations=tuple(pitch_observations),
            range_observations=tuple(range_observations),
            note_observations=tuple(note_observations),
            audio_observations=tuple(audio_observations),
            exercises=(
                "Hold one comfortable note for five seconds and watch the live tuner "
                "while you do it.",
            ),
            practice_plan=("Configure a real feedback provider to replace this demo response.",),
            provenance=MOCK_PROVENANCE,
        )
